version: "3"
services:
  sickbeard:
    build: 
      context: .
      dockerfile: ./docker/linux/Dockerfile #Change this to windows in case of a windows container
    image: junalmeida/sickbeard

    container_name: sickbeard
    restart: always
    volumes:
      - ./docker/data/:/src/sickbeard/runtime
    ports:
      - "8081:8081" #You can redirect this to 80, or use a web server with ssl